import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createFamilyApi} from './family-api.mjs';

test('family sharing enforces roles, publication, expiry, revocation and durable storage',async t=>{
  const directory=await mkdtemp(join(tmpdir(),'shimboku-family-test-'));
  let handler,clock=Date.now();
  const server=createServer((req,res)=>handler(req,res));
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const origin=`http://127.0.0.1:${server.address().port}`;
  handler=await createFamilyApi({directory,origin,now:()=>clock});
  t.after(async()=>{await new Promise(resolve=>server.close(resolve));await rm(directory,{recursive:true,force:true});});
  const call=async(path,method='GET',payload={},cookie='',requestOrigin=origin)=>{
    const response=await fetch(origin+'/api/family'+path,{method,headers:{...(method!=='GET'?{'Content-Type':'application/json',Origin:requestOrigin}:{}),...(cookie?{Cookie:cookie}:{})},...(method==='GET'?{}:{body:JSON.stringify(payload)})});
    return {status:response.status,body:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0],rawCookie:response.headers.get('set-cookie')};
  };
  assert.equal((await call('/owner')).status,401);
  const created=await call('/create','POST');assert.equal(created.status,200);
  const owner=created.cookie;assert.match(created.rawCookie,/HttpOnly; SameSite=Strict/);
  assert.equal((await call('/candidates','PUT',{ids:['ecology'],notes:{ecology:'SECRET'}},owner)).status,200);
  assert.equal((await call('/candidates','PUT',{ids:['food']},owner,'https://attacker.example')).status,403);
  assert.equal((await call('/candidates','PUT',{ids:['ecology-event']},owner)).status,400);
  const invited=await call('/invite','POST',{},owner);
  const secret=new URL(invited.body.url).hash.slice('#invite='.length);
  const joined=await call('/join','POST',{token:secret});const viewer=joined.cookie;
  assert.equal(joined.status,200);assert.deepEqual(joined.body.candidates,[{id:'ecology',name:'生態学',domain:'ecology'}]);
  assert.ok(!JSON.stringify(joined.body).includes('SECRET'));
  assert.equal((await call('/join','POST',{token:secret})).status,410);
  assert.equal((await call('/owner','GET',{},viewer)).status,401);
  assert.equal((await call('/viewer','GET',{},owner)).status,401);
  const otherOwner=(await call('/create','POST')).cookie;
  assert.deepEqual((await call('/owner','GET',{},otherOwner)).body.ids,[]);
  const suggestion={requestId:randomUUID(),target:'ecology',title:'Try observing',message:'If you want',url:'https://example.org',photo:'',tags:['ecology'],kind:'読みもの'};
  assert.equal((await call('/recommendations','POST',{...suggestion,target:'food'},viewer)).status,409);
  assert.equal((await call('/recommendations','POST',{...suggestion,url:'javascript:alert(1)'},viewer)).status,400);
  assert.equal((await call('/recommendations','POST',suggestion,viewer)).status,200);
  assert.equal((await call('/recommendations','POST',suggestion,viewer)).status,200);
  const inbox=(await call('/owner','GET',{},owner)).body.recommendations;assert.equal(inbox.length,1);assert.equal(inbox[0].status,'new');
  assert.equal((await call('/viewer','GET',{},viewer)).body.recommendations,undefined);
  handler=await createFamilyApi({directory,origin,now:()=>clock});
  assert.equal((await call('/owner','GET',{},owner)).body.recommendations.length,1);
  const persisted=await readFile(join(directory,'families.json'),'utf8');
  assert.ok(!persisted.includes(secret));assert.ok(!persisted.includes(owner.split('=')[1]));assert.ok(!persisted.includes(viewer.split('=')[1]));
  await call('/candidates','PUT',{ids:[]},owner);
  assert.deepEqual((await call('/viewer','GET',{},viewer)).body.candidates,[]);
  assert.equal((await call('/recommendations','POST',{...suggestion,requestId:randomUUID()},viewer)).status,409);
  await call('/access','DELETE',{},owner);
  assert.equal((await call('/viewer','GET',{},viewer)).status,401);
  assert.equal((await call('/recommendations','POST',suggestion,viewer)).status,401);
  assert.equal((await call('/space','DELETE',{},otherOwner)).status,200);
  assert.equal((await call('/owner','GET',{},otherOwner)).status,401);
  const expiring=await call('/invite','POST',{},owner);clock+=86400001;
  assert.equal((await call('/join','POST',{token:new URL(expiring.body.url).hash.slice(8)})).status,410);
  clock+=30*86400000;assert.equal((await call('/owner','GET',{},owner)).status,401);
});
