import {evidenceFor,inquiryCandidates,nextInquiryStep} from './inquiry.mjs';
const escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export function renderInquiryRecord(node,items) {
  const record=node.inquiry || {};
  return `<form id="inquiry-record"><h3>ひとことメモ</h3><label>やってみたいこと<textarea name="plan" maxlength="1500" placeholder="例：好きな曲を友達と弾いてみたい">${escape(record.plan || '')}</textarea></label><label>やってみた感想<textarea name="observation" maxlength="1500" placeholder="例：一緒に音が合ったときが楽しかった">${escape(record.observation || '')}</textarea></label><label>いまの気持ち<select name="status">${[['considering','気になっている'],['planned','やってみたい'],['tried','やってみた'],['paused','あとで']].map(([value,label])=>`<option value="${value}" ${(record.status || 'considering')===value?'selected':''}>${label}</option>`).join('')}</select></label><details class="record-more"><summary>ほかにもメモする</summary><label>気になっていること<input name="question" maxlength="1500" value="${escape(record.question || '')}"></label><label>わかったこと<textarea name="learned" maxlength="1500">${escape(record.learned || '')}</textarea></label><label>次にやってみたいこと<textarea name="next" maxlength="1500">${escape(record.next || '')}</textarea></label></details><p class="subtle" id="inquiry-record-status">全部書かなくても保存できます。</p><button class="primary block">メモを保存</button></form>`;
}

export function renderInquiryComparison(map,parent,items) {
  const root=map.nodes.find(node=>node.id===parent),nodes=inquiryCandidates(map,parent,items);
  const criteria=root.inquiry?.criteria || ['自分が面白そうと思うところ','続けるうえで気になること'];
  const evidence=nodes.map(node=>evidenceFor(node,items));
  const rows=[['何ができる・学べる','summary'],['費用','cost'],['対象・参加条件','eligibility'],['場所・必要なもの','location']];
  return `<p class="dialog-note">「${escape(root.title)}」につながる${nodes.length}件を整理します。活動と学校など、役割の違う気になるものも含みます。優劣の順位はつけません。</p><form id="inquiry-question"><label>気になっていること<input name="question" maxlength="1500" value="${escape(root.inquiry?.question || root.title)}" required></label><label>並べて見たいこと（1行に1つ・最大5つ）<textarea name="criteria" rows="3" maxlength="404">${escape(criteria.join('\n'))}</textarea></label><button class="secondary">見るポイントを保存</button></form>${nodes.length?`<form id="inquiry-assessment"><div class="inquiry-table-scroll" tabindex="0" role="region" aria-label="出典と自分のメモを比べる表。横にスクロールできます"><table class="inquiry-table"><thead><tr><th scope="col">比べる内容</th>${nodes.map((node,i)=>`<th scope="col">${escape(node.title)}<small>${escape(evidence[i].kind)}</small></th>`).join('')}</tr></thead><tbody><tr class="inquiry-section"><th colspan="${nodes.length+1}">掲載情報から整理した事実 · 外部URLだけの項目は未確認です</th></tr>${rows.map(([title,key])=>`<tr><th scope="row">${title}</th>${evidence.map(item=>`<td>${escape(item[key])}</td>`).join('')}</tr>`).join('')}<tr><th scope="row">出典</th>${evidence.map(item=>`<td>${item.url?`<a href="${escape(item.url)}" target="_blank" rel="noopener noreferrer">${escape(item.original)} ↗</a>`:'写真・元資料で確認'}${item.checkedOn?`<small>確認 ${escape(item.checkedOn)}</small>`:''}</td>`).join('')}</tr><tr class="inquiry-section"><th colspan="${nodes.length+1}">自分のメモ · 体験や根拠を書きながら比べる</th></tr>${criteria.map((criterion,index)=>`<tr><th scope="row">${escape(criterion)}</th>${nodes.map(node=>`<td><textarea data-assess-node="${node.id}" data-assess-axis="${index}" aria-label="${escape(node.title)}：${escape(criterion)}" maxlength="500" placeholder="まだわからない、でも大丈夫">${escape(node.inquiry?.answers?.[criterion] || '')}</textarea></td>`).join('')}</tr>`).join('')}<tr><th scope="row">体験からわかったこと</th>${nodes.map(node=>`<td>${escape(node.inquiry?.learned || 'まだ記録がありません')}<small>${escape(node.inquiry?.observation || '')}</small><button type="button" class="text-button" data-inquiry-experience="${node.id}">試す計画・体験を記録 →</button></td>`).join('')}</tr><tr><th scope="row">次に確かめること</th>${nodes.map(node=>`<td>${escape(nextInquiryStep(node,items).text)}</td>`).join('')}</tr></tbody></table></div><p id="inquiry-assessment-status" role="status">自分のメモを保存すると、次に並べたときにも残ります。</p><button class="primary">自分のメモを保存</button></form>`:'<div class="empty"><p>まずはここに、教材・活動・学校などを追加してください。追加した気になるものが一覧に集まります。</p><button class="primary" data-close="inquiry-dialog">情報を探しに戻る</button></div>'}<p id="inquiry-error" role="alert"></p>`;
}
