// Generated by npm run knowledge:build. Edit data/knowledge.json instead.
export default {
  "verbs": [
    {
      "id": "make",
      "label": "つくる",
      "icon": "✎",
      "summary": "なかったものを、手を動かして出す。",
      "detail": "作ったものは残る。うまくいかなくても、直す場所が見える。",
      "domains": [
        "media",
        "design",
        "information",
        "engineering",
        "food",
        "sound"
      ]
    },
    {
      "id": "compare",
      "label": "くらべる",
      "icon": "⇄",
      "summary": "2つ並べて、違いを1つ見つける。",
      "detail": "「どっちが好きか」ではなく「どこが違うか」を言えると、次に調べることが決まる。",
      "domains": [
        "ecology",
        "food",
        "sound",
        "design",
        "environment"
      ]
    },
    {
      "id": "observe",
      "label": "観察する",
      "icon": "◉",
      "summary": "よく見て、気づいたことを残す。",
      "detail": "見た回数ではなく、残した記録が増える。あとから自分で読み返せる。",
      "domains": [
        "ecology",
        "environment",
        "design"
      ]
    },
    {
      "id": "dig",
      "label": "調べる",
      "icon": "⌕",
      "summary": "仕組みや理由を、元の資料まで追う。",
      "detail": "答えを覚えるのではなく、どこに書いてあったかが分かる。",
      "domains": [
        "ecology",
        "environment",
        "food",
        "sound",
        "engineering",
        "information"
      ]
    },
    {
      "id": "tell",
      "label": "伝える",
      "icon": "➤",
      "summary": "人にわかる形に、いちど直す。",
      "detail": "説明しようとすると、自分が分かっていない場所が出てくる。",
      "domains": [
        "media",
        "design",
        "information",
        "environment"
      ]
    }
  ],
  "domains": {
    "ecology": {
      "name": "生態学",
      "question": "生き物の暮らしを知りたい",
      "summary": "生き物と、その周りの環境との関係を探る。",
      "example": "同じ海岸でも、場所によって生き物が違うのはなぜ？",
      "method": "観察する · 記録する",
      "tags": [
        "フィールド観察",
        "比較",
        "データ分析"
      ],
      "learning": "生物の暮らしや環境を観察し、記録を比べて関係を考える。"
    },
    "environment": {
      "name": "環境科学",
      "question": "環境の変化を知りたい",
      "summary": "環境が変わる仕組みを調べ、課題への関わり方を考える。",
      "example": "海や川の変化を知るには、何を測り、どう比べればいい？",
      "method": "測る · 調べる",
      "tags": [
        "観測",
        "実験",
        "データ分析"
      ],
      "learning": "自然の仕組みと人の活動を、観測や分析を通して考える。"
    },
    "engineering": {
      "name": "海洋工学",
      "question": "海で使う仕組みを作りたい",
      "summary": "海という環境で役立つ技術や仕組みを考える。",
      "example": "海で観測を続けられる機械は、どう作る？",
      "method": "設計する · 作る",
      "tags": [
        "設計",
        "実験",
        "プログラミング"
      ],
      "learning": "海の条件を考慮しながら、機械やシステムを設計して確かめる。"
    },
    "information": {
      "name": "情報科学",
      "question": "仕組みを考えて動かしたい",
      "summary": "情報を扱う仕組みを考え、課題を解く方法を探る。",
      "example": "ゲームのキャラクターを、キーを押した方向へ動かすには？",
      "method": "組み立てる · 分析する",
      "tags": [
        "プログラミング",
        "モデル化",
        "データ分析"
      ],
      "learning": "情報の表し方や処理の方法を学び、問題を分解して考える。"
    },
    "design": {
      "name": "デザイン",
      "question": "使いやすさを考えたい",
      "summary": "使う人や状況を理解し、形や体験を考える。",
      "example": "はじめての人でも使える道具にするには？",
      "method": "観察する · 試作する",
      "tags": [
        "観察",
        "試作",
        "表現"
      ],
      "learning": "人の行動や課題を調べ、試作と検証で改善する。"
    },
    "food": {
      "name": "食品科学",
      "question": "おいしさの仕組みを知りたい",
      "summary": "食材が変わる仕組みや、食品を作り届ける方法を調べる。",
      "example": "同じ牛乳から、チーズとヨーグルトができるのはなぜ？",
      "method": "比べる · 実験する",
      "tags": [
        "食品",
        "微生物",
        "化学"
      ],
      "learning": "成分や微生物の働き、加工・保存の技術を学ぶ。料理の技術だけでなく、食品の仕組みを扱う。"
    },
    "sound": {
      "name": "音響・音楽",
      "question": "好きな音を探したい",
      "summary": "音の生まれ方、聞こえ方、音楽としての表現を考える。",
      "example": "同じフレーズでも、ギターの音色で印象が変わるのはなぜ？",
      "method": "聴き比べる · 記録する",
      "tags": [
        "音楽",
        "振動",
        "聴覚"
      ],
      "learning": "音の物理的な性質と、人の感じ方、文化や表現を行き来する。演奏だけに限らない学び方がある。"
    },
    "media": {
      "shortName": "映像・表現",
      "name": "映像・ゲーム表現",
      "question": "遊びや物語を作りたい",
      "summary": "映像・ゲーム・物語で、どんな体験を届けるか考える。",
      "example": "ゲームの説明を読まなくても、操作がわかるのはなぜ？",
      "method": "作る · 遊んで確かめる",
      "tags": [
        "ゲーム",
        "映像",
        "物語"
      ],
      "learning": "映像や音、ルールの組み合わせが体験にどう影響するか、作品を作りながら考える。"
    }
  },
  "concepts": [
    {
      "id": "biology",
      "label": "生き物の世界",
      "kind": "field",
      "summary": "海だけでなく、森・川・身近な場所の生き物にも目を向ける。",
      "domains": [
        "ecology"
      ],
      "broader": [],
      "related": [
        "fieldwork",
        "marine-life",
        "forest-life",
        "freshwater-life",
        "urban-nature",
        "plant-life",
        "insect-life",
        "bird-life",
        "microbe-life"
      ]
    },
    {
      "id": "fieldwork",
      "label": "外に出て観察する",
      "kind": "activity",
      "summary": "生き物や環境を現地で観察し、写真や記録から違いを探す。",
      "domains": [
        "ecology",
        "environment"
      ],
      "broader": [],
      "related": [
        "marine-life",
        "forest-life",
        "freshwater-life",
        "urban-nature",
        "record-keeping",
        "citizen-survey"
      ]
    },
    {
      "id": "marine-life",
      "label": "海の生き物",
      "kind": "subject",
      "summary": "海辺や海の中の生き物と、すんでいる環境を知る。",
      "domains": [
        "ecology",
        "environment"
      ],
      "broader": [
        "biology"
      ],
      "related": [
        "fieldwork",
        "freshwater-life",
        "ecology-links",
        "environment-living",
        "bird-life"
      ]
    },
    {
      "id": "forest-life",
      "label": "森・里山の生き物",
      "kind": "subject",
      "summary": "植物・昆虫・鳥など、陸の生き物のつながりに目を向ける。",
      "domains": [
        "ecology",
        "environment"
      ],
      "broader": [
        "biology"
      ],
      "related": [
        "fieldwork",
        "freshwater-life",
        "plant-life",
        "insect-life",
        "forest-care"
      ]
    },
    {
      "id": "freshwater-life",
      "label": "川・池の生き物",
      "kind": "subject",
      "summary": "身近な水辺で、生き物と水の環境の関係を知る。",
      "domains": [
        "ecology",
        "environment"
      ],
      "broader": [
        "biology"
      ],
      "related": [
        "fieldwork",
        "marine-life",
        "citizen-survey",
        "environment-living"
      ]
    },
    {
      "id": "urban-nature",
      "label": "街の中の自然",
      "kind": "subject",
      "summary": "公園・校庭・街路樹・用水路など、通学路のそばにいる生き物を見る。",
      "domains": [
        "ecology",
        "environment"
      ],
      "broader": [],
      "related": [
        "fieldwork",
        "insect-life",
        "bird-life",
        "plant-life",
        "citizen-survey"
      ]
    },
    {
      "id": "plant-life",
      "label": "植物のこと",
      "kind": "subject",
      "summary": "花・木・草の形やくらしを比べる。育つ場所によって姿が変わる。",
      "domains": [
        "ecology"
      ],
      "broader": [
        "biology"
      ],
      "related": [
        "fieldwork",
        "forest-life",
        "urban-nature"
      ]
    },
    {
      "id": "insect-life",
      "label": "虫のこと",
      "kind": "subject",
      "summary": "昆虫やクモなど、身近で数も種類も多い生き物を見分ける。",
      "domains": [
        "ecology"
      ],
      "broader": [
        "biology"
      ],
      "related": [
        "fieldwork",
        "urban-nature",
        "forest-life"
      ]
    },
    {
      "id": "bird-life",
      "label": "鳥のこと",
      "kind": "subject",
      "summary": "季節で入れかわる鳥を、姿と声から見分ける。街でも海でも観察できる。",
      "domains": [
        "ecology"
      ],
      "broader": [
        "biology"
      ],
      "related": [
        "fieldwork",
        "urban-nature",
        "marine-life"
      ]
    },
    {
      "id": "microbe-life",
      "label": "目に見えない生き物",
      "kind": "subject",
      "summary": "発酵や土のはたらきを支える菌や微生物。台所からも生物学につながる。",
      "domains": [
        "food",
        "ecology"
      ],
      "broader": [
        "biology"
      ],
      "related": [
        "ecology-links"
      ]
    },
    {
      "id": "ecology-links",
      "label": "生き物と環境のつながり",
      "kind": "field",
      "summary": "食べる・食べられる、すみかの変化など、生き物どうしと環境の関係を見る。",
      "domains": [
        "ecology",
        "environment"
      ],
      "broader": [
        "biology"
      ],
      "related": [
        "environment-living",
        "fieldwork",
        "microbe-life"
      ]
    },
    {
      "id": "environment-living",
      "label": "環境と暮らし",
      "kind": "field",
      "summary": "ごみ・水・気候など、人の暮らしが自然に与える影響を考える。",
      "domains": [
        "environment"
      ],
      "broader": [],
      "related": [
        "ecology-links",
        "citizen-survey",
        "forest-care"
      ]
    },
    {
      "id": "sound-science",
      "label": "音のしくみ",
      "kind": "field",
      "summary": "音がどう生まれ、どう伝わるかを、楽器や録音から考える。",
      "domains": [
        "sound",
        "engineering"
      ],
      "broader": [],
      "related": [
        "making-things"
      ]
    },
    {
      "id": "record-keeping",
      "label": "記録してまとめる",
      "kind": "activity",
      "summary": "見つけたことを写真・数字・言葉で残し、あとから比べられる形にする。",
      "domains": [
        "information",
        "media"
      ],
      "broader": [],
      "related": [
        "fieldwork",
        "research-challenge",
        "making-things"
      ]
    },
    {
      "id": "citizen-survey",
      "label": "みんなで調べる",
      "kind": "activity",
      "summary": "同じ方法で各地の人が観察し、結果を持ち寄る調査に参加する。",
      "domains": [
        "environment",
        "ecology"
      ],
      "broader": [],
      "related": [
        "fieldwork",
        "record-keeping",
        "freshwater-life",
        "urban-nature"
      ]
    },
    {
      "id": "research-challenge",
      "label": "自分の研究にする",
      "kind": "activity",
      "summary": "気づいたことを問いにして、確かめる方法まで自分で考える。",
      "domains": [
        "information",
        "ecology"
      ],
      "broader": [],
      "related": [
        "record-keeping",
        "fieldwork",
        "making-things"
      ]
    },
    {
      "id": "forest-care",
      "label": "森や里山を手入れする",
      "kind": "activity",
      "summary": "下草刈りや植樹など、人が手を入れて保たれてきた場所に関わる。",
      "domains": [
        "environment",
        "ecology"
      ],
      "broader": [],
      "related": [
        "forest-life",
        "fieldwork",
        "environment-living"
      ]
    },
    {
      "id": "making-things",
      "label": "つくって試す",
      "kind": "activity",
      "summary": "作品や道具を自分で組み立て、動かしながら直していく。",
      "domains": [
        "information",
        "design",
        "sound"
      ],
      "broader": [],
      "related": [
        "record-keeping",
        "sound-science"
      ]
    }
  ],
  "topics": {
    "games": {
      "label": "ゲーム",
      "root": "ゲームが好き",
      "ids": [
        "information",
        "media",
        "design"
      ],
      "title": "「ゲームが好き」の、その先。",
      "keywords": [
        "ゲーム",
        "げーむ",
        "マイクラ",
        "マインクラフト",
        "scratch",
        "スクラッチ",
        "プログラミング"
      ],
      "questions": {
        "information": "自分で動く仕組みを作る",
        "media": "物語や世界観を作る",
        "design": "遊びやすさを考える"
      }
    },
    "cooking": {
      "label": "料理・食べもの",
      "root": "料理が好き",
      "ids": [
        "food",
        "ecology",
        "design"
      ],
      "title": "「おいしい」の、その先。",
      "keywords": [
        "料理",
        "りょうり",
        "食べ物",
        "食べもの",
        "お菓子",
        "パン",
        "発酵",
        "食品",
        "食材"
      ],
      "questions": {
        "food": "食材が変わる理由を知る",
        "ecology": "微生物の働きを知る",
        "design": "食べる体験を考える"
      }
    },
    "music": {
      "label": "ギター・音楽",
      "root": "音楽が好き",
      "ids": [
        "sound",
        "information",
        "design"
      ],
      "title": "「好きな音」の、その先。",
      "keywords": [
        "ギター",
        "ぎたー",
        "音楽",
        "おんがく",
        "バンド",
        "作曲",
        "楽器",
        "音響"
      ],
      "questions": {
        "sound": "音色や響きを知る",
        "information": "音をデータで扱う",
        "design": "楽器の形を考える"
      }
    },
    "sea": {
      "label": "海・生き物",
      "root": "海が好き",
      "ids": [
        "ecology",
        "environment",
        "engineering"
      ],
      "title": "「海が好き」の、その先。",
      "keywords": [
        "海",
        "うみ",
        "魚",
        "さかな",
        "生き物",
        "生物",
        "水族館",
        "深海",
        "自然",
        "観察"
      ],
      "questions": {
        "ecology": "生き物の暮らしを知る",
        "environment": "環境の変化を知る",
        "engineering": "海で使う技術を作る"
      }
    }
  },
  "directions": {
    "music": [
      {
        "id": "together",
        "icon": "♫",
        "title": "一緒に演奏する",
        "description": "人と音を合わせる楽しさ。人数や発表の仕方でも変わる。",
        "domains": [
          "sound",
          "media"
        ],
        "activities": [
          {
            "id": "music-together-0",
            "title": "友達と一曲",
            "description": "二人でコードとメロディーを分担する。",
            "label": "身近な人と",
            "verb": "make",
            "minutes": 30,
            "athome": false,
            "topic": "music"
          },
          {
            "id": "music-together-1",
            "title": "バンドを組む",
            "description": "好きな曲を持ち寄り、役割や練習方法を相談する。",
            "label": "チームで",
            "verb": "tell",
            "minutes": 30,
            "athome": false,
            "topic": "music"
          },
          {
            "id": "music-together-2",
            "title": "映像で共演する",
            "description": "別々に録った音や映像を重ねて、一つの作品にする。",
            "label": "離れた場所から",
            "verb": "make",
            "minutes": 60,
            "athome": true,
            "topic": "music"
          }
        ]
      },
      {
        "id": "grow",
        "icon": "↗",
        "title": "上達する",
        "description": "速く弾くことだけが上達ではない。自分の「こう弾きたい」を探そう。",
        "domains": [
          "sound"
        ],
        "activities": [
          {
            "id": "music-grow-0",
            "title": "一曲を弾き切る",
            "description": "好きな曲の短い部分を選び、昨日の録音と聴き比べる。",
            "label": "自分のペースで",
            "verb": "observe",
            "minutes": 15,
            "athome": true,
            "topic": "music"
          },
          {
            "id": "music-grow-1",
            "title": "耳で音を探す",
            "description": "短いメロディーを聴き、楽器で同じ音を探す。",
            "label": "聴く力から",
            "verb": "observe",
            "minutes": 15,
            "athome": true,
            "topic": "music"
          },
          {
            "id": "music-grow-2",
            "title": "人に聴いてもらう",
            "description": "弾いた録音を信頼できる人に聴いてもらい、伝わり方を聞く。",
            "label": "対話しながら",
            "verb": "tell",
            "minutes": 15,
            "athome": true,
            "topic": "music"
          }
        ]
      },
      {
        "id": "cross",
        "icon": "✦",
        "title": "音楽と異分野",
        "description": "弾く人から、音を作る人・届ける人へ。",
        "domains": [
          "sound",
          "information",
          "design",
          "media"
        ],
        "activities": [
          {
            "id": "music-cross-0",
            "title": "音楽 × ゲーム",
            "description": "同じ場面に違う音を合わせ、印象の変化を比べる。",
            "label": "表現をつくる",
            "verb": "compare",
            "minutes": 20,
            "athome": true,
            "topic": "music"
          },
          {
            "id": "music-cross-1",
            "title": "音楽 × ものづくり",
            "description": "弦や箱の形と音の違いを調べ、楽器の仕組みを図にする。",
            "label": "仕組みを知る",
            "verb": "dig",
            "minutes": 30,
            "athome": true,
            "topic": "music"
          },
          {
            "id": "music-cross-2",
            "title": "音楽 × 場づくり",
            "description": "小さな演奏会を想像し、曲順・照明・客席を考える。",
            "label": "体験を届ける",
            "verb": "make",
            "minutes": 20,
            "athome": true,
            "topic": "music"
          }
        ]
      }
    ],
    "games": [
      {
        "id": "together",
        "icon": "◉",
        "title": "誰かと楽しむ",
        "description": "遊び方や場づくりにも、自分らしさがある。",
        "domains": [
          "media",
          "design"
        ],
        "activities": [
          {
            "id": "games-together-0",
            "title": "友達と遊ぶ会",
            "description": "みんなが参加しやすいルールを考える。",
            "label": "身近な人と",
            "verb": "make",
            "minutes": 30,
            "athome": false,
            "topic": "games"
          },
          {
            "id": "games-together-1",
            "title": "遊び方を伝える",
            "description": "初心者向けに短い攻略や説明を作る。",
            "label": "人に伝える",
            "verb": "tell",
            "minutes": 20,
            "athome": true,
            "topic": "games"
          },
          {
            "id": "games-together-2",
            "title": "大会を企画する",
            "description": "参加条件や時間割を考え、小さな企画にする。",
            "label": "場をつくる",
            "verb": "make",
            "minutes": 30,
            "athome": false,
            "topic": "games"
          }
        ]
      },
      {
        "id": "make",
        "icon": "✎",
        "title": "自分でつくる",
        "description": "仕組み・物語・見た目。作りたい部分から入れる。",
        "domains": [
          "information",
          "media",
          "design"
        ],
        "activities": [
          {
            "id": "games-make-0",
            "title": "動きを作る",
            "description": "ボタンを押すと動く、小さな仕掛けを作る。",
            "label": "仕組みから",
            "verb": "make",
            "minutes": 30,
            "athome": true,
            "topic": "games"
          },
          {
            "id": "games-make-1",
            "title": "世界観を描く",
            "description": "主人公と舞台を一枚にまとめる。",
            "label": "物語から",
            "verb": "make",
            "minutes": 20,
            "athome": true,
            "topic": "games"
          },
          {
            "id": "games-make-2",
            "title": "遊んでもらう",
            "description": "作ったものを人に試してもらい、一つ直す。",
            "label": "人の反応から",
            "verb": "tell",
            "minutes": 20,
            "athome": false,
            "topic": "games"
          }
        ]
      },
      {
        "id": "cross",
        "icon": "✦",
        "title": "ゲームと異分野",
        "description": "遊ぶ経験が、別の問いにつながる。",
        "domains": [
          "information",
          "sound",
          "design"
        ],
        "activities": [
          {
            "id": "games-cross-0",
            "title": "ゲーム × 音楽",
            "description": "効果音を変えて、操作の印象を比べる。",
            "label": "音から",
            "verb": "compare",
            "minutes": 15,
            "athome": true,
            "topic": "games"
          },
          {
            "id": "games-cross-1",
            "title": "ゲーム × 学び",
            "description": "覚えたいことを遊びのルールに変える。",
            "label": "学びから",
            "verb": "make",
            "minutes": 20,
            "athome": true,
            "topic": "games"
          },
          {
            "id": "games-cross-2",
            "title": "ゲーム × デザイン",
            "description": "文字や色の違いで遊びやすさが変わるか考える。",
            "label": "使いやすさから",
            "verb": "compare",
            "minutes": 15,
            "athome": true,
            "topic": "games"
          }
        ]
      }
    ],
    "cooking": [
      {
        "id": "share",
        "icon": "♡",
        "title": "誰かに作る",
        "description": "食べる相手や場面から料理を考える。",
        "domains": [
          "food",
          "design"
        ],
        "activities": [
          {
            "id": "cooking-share-0",
            "title": "家族の一皿",
            "description": "好きな味を聞いて、献立を考える。",
            "label": "身近な人に",
            "verb": "make",
            "minutes": 30,
            "athome": true,
            "topic": "cooking"
          },
          {
            "id": "cooking-share-1",
            "title": "持ち寄りを企画",
            "description": "分担や予算を決める。アレルギーも先に確認する。",
            "label": "みんなで",
            "verb": "tell",
            "minutes": 20,
            "athome": false,
            "topic": "cooking"
          },
          {
            "id": "cooking-share-2",
            "title": "レシピを伝える",
            "description": "作り方を写真や図でわかりやすくまとめる。",
            "label": "知らない人にも",
            "verb": "tell",
            "minutes": 30,
            "athome": true,
            "topic": "cooking"
          }
        ]
      },
      {
        "id": "grow",
        "icon": "↗",
        "title": "味を探究する",
        "description": "手順・材料・感覚の違いに目を向ける。",
        "domains": [
          "food"
        ],
        "activities": [
          {
            "id": "cooking-grow-0",
            "title": "味を言葉にする",
            "description": "同じ食品の味や香りを比べて記録する。",
            "label": "感じる",
            "verb": "observe",
            "minutes": 15,
            "athome": true,
            "topic": "cooking"
          },
          {
            "id": "cooking-grow-1",
            "title": "レシピを比べる",
            "description": "同じ料理の材料や手順の違いを探す。",
            "label": "調べる",
            "verb": "compare",
            "minutes": 15,
            "athome": true,
            "topic": "cooking"
          },
          {
            "id": "cooking-grow-2",
            "title": "自分の一皿を考える",
            "description": "比較で気づいたことを、次の献立に生かす。",
            "label": "工夫する",
            "verb": "make",
            "minutes": 20,
            "athome": true,
            "topic": "cooking"
          }
        ]
      },
      {
        "id": "cross",
        "icon": "✦",
        "title": "食と異分野",
        "description": "一皿から、生き物や地域にもつながる。",
        "domains": [
          "food",
          "ecology",
          "environment"
        ],
        "activities": [
          {
            "id": "cooking-cross-0",
            "title": "食 × 生物",
            "description": "発酵食品を調べ、微生物の役割を知る。",
            "label": "科学から",
            "verb": "dig",
            "minutes": 20,
            "athome": true,
            "topic": "cooking"
          },
          {
            "id": "cooking-cross-1",
            "title": "食 × 地域",
            "description": "郷土料理と土地のつながりを調べる。",
            "label": "文化から",
            "verb": "dig",
            "minutes": 20,
            "athome": true,
            "topic": "cooking"
          },
          {
            "id": "cooking-cross-2",
            "title": "食 × 環境",
            "description": "冷蔵庫の食材を使い切る献立を考える。",
            "label": "暮らしから",
            "verb": "make",
            "minutes": 15,
            "athome": true,
            "topic": "cooking"
          }
        ]
      }
    ],
    "sea": [
      {
        "id": "observe",
        "icon": "◎",
        "title": "生き物を知る",
        "description": "見つける・比べる・伝える楽しさ。",
        "domains": [
          "ecology"
        ],
        "activities": [
          {
            "id": "sea-observe-0",
            "title": "写真から観察",
            "description": "生き物の写真を見て、形の違いを探す。",
            "label": "家から",
            "verb": "observe",
            "minutes": 15,
            "athome": true,
            "topic": "sea"
          },
          {
            "id": "sea-observe-1",
            "title": "水族館で比べる",
            "description": "同じ水槽の生き物の動きを見比べる。",
            "label": "現地で",
            "verb": "compare",
            "minutes": 60,
            "athome": false,
            "topic": "sea"
          },
          {
            "id": "sea-observe-2",
            "title": "観察をまとめる",
            "description": "気づいた違いを、自分の図鑑にする。",
            "label": "伝える",
            "verb": "tell",
            "minutes": 20,
            "athome": true,
            "topic": "sea"
          }
        ]
      },
      {
        "id": "protect",
        "icon": "♡",
        "title": "海と暮らしを考える",
        "description": "遠い環境問題を、身近な問いに変える。",
        "domains": [
          "environment",
          "ecology"
        ],
        "activities": [
          {
            "id": "sea-protect-0",
            "title": "ごみの行方",
            "description": "身近なごみが水辺に届く経路を調べる。",
            "label": "暮らしから",
            "verb": "dig",
            "minutes": 20,
            "athome": true,
            "topic": "sea"
          },
          {
            "id": "sea-protect-1",
            "title": "地域の活動を知る",
            "description": "海岸清掃などの活動内容と参加条件を調べる。",
            "label": "地域から",
            "verb": "dig",
            "minutes": 15,
            "athome": true,
            "topic": "sea"
          },
          {
            "id": "sea-protect-2",
            "title": "伝え方を考える",
            "description": "調べたことを一枚のポスターにする。",
            "label": "表現から",
            "verb": "tell",
            "minutes": 30,
            "athome": true,
            "topic": "sea"
          }
        ]
      },
      {
        "id": "cross",
        "icon": "✦",
        "title": "海と異分野",
        "description": "食・機械・データからも海に近づける。",
        "domains": [
          "engineering",
          "food",
          "information"
        ],
        "activities": [
          {
            "id": "sea-cross-0",
            "title": "海 × 食",
            "description": "食卓の魚の産地と流通を調べる。",
            "label": "食から",
            "verb": "dig",
            "minutes": 20,
            "athome": true,
            "topic": "sea"
          },
          {
            "id": "sea-cross-1",
            "title": "海 × 技術",
            "description": "水中ロボットは何を調べるのか探す。",
            "label": "ものづくりから",
            "verb": "dig",
            "minutes": 15,
            "athome": true,
            "topic": "sea"
          },
          {
            "id": "sea-cross-2",
            "title": "海 × データ",
            "description": "海の温度や生物の記録を、図にして眺める。",
            "label": "情報から",
            "verb": "observe",
            "minutes": 20,
            "athome": true,
            "topic": "sea"
          }
        ]
      }
    ]
  },
  "resources": {
    "ocean-steam": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "environment",
        "engineering"
      ],
      "group": "try",
      "kind": "自宅・教材",
      "type": "resource",
      "name": "海の不思議を、ひとつ読む",
      "summary": "写真やワークシートから、海の生き物と地球環境の関係に触れる。",
      "url": "https://www.jamstec.go.jp/steam/",
      "source": "JAMSTEC",
      "checkedOn": "2026-09-11",
      "example": false,
      "online": true,
      "free": true,
      "conditions": [
        [
          "対象",
          "小中学生向けの教材など。巻ごとに対象が異なります。"
        ],
        [
          "費用",
          "教材のダウンロードは無料"
        ],
        [
          "場所",
          "オンライン・家庭学習でも利用可"
        ]
      ],
      "reason": "海の写真・観測・環境の問いを扱う教材。生き物と環境のつながりを、観察する視点で考えられます。",
      "step": "教材の見出しから、気になる問いを1つ選ぶ。",
      "conceptIds": [
        "marine-life",
        "environment-living"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "dig",
        "observe"
      ]
    },
    "scratch-create": {
      "domain": "information",
      "domains": [
        "information",
        "media",
        "design"
      ],
      "group": "try",
      "kind": "自宅・制作",
      "type": "resource",
      "name": "Scratchで小さな作品を作る",
      "summary": "ブロックを組み合わせて、キャラクター・音・動きを作る。",
      "url": "https://scratch.mit.edu/ideas",
      "source": "Scratch Foundation",
      "checkedOn": "2026-09-11",
      "example": false,
      "online": true,
      "free": true,
      "conditions": [
        [
          "費用",
          "Scratchの利用は無料"
        ],
        [
          "機器",
          "制作にはPC・タブレット推奨"
        ],
        [
          "公開",
          "作品の公開・アカウント設定は外部サイトで確認"
        ]
      ],
      "keywords": [
        "ゲーム",
        "スクラッチ",
        "プログラミング"
      ],
      "reason": "プログラムの順番と、絵・音による表現を同時に試せます。遊びを作る入口にもなります。",
      "step": "気になるチュートリアルを1つ開き、動きか音を1つ変えてみる。",
      "conceptIds": [
        "making-things"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "make"
      ]
    },
    "coderdojo": {
      "domain": "information",
      "domains": [
        "information",
        "media"
      ],
      "group": "continue",
      "kind": "学外・継続活動",
      "type": "community",
      "name": "近くのCoderDojoを探す",
      "summary": "学校の外で、プログラミングや電子工作を主体的に学ぶ活動。",
      "url": "https://coderdojo.jp/",
      "source": "CoderDojo Japan",
      "checkedOn": "2026-09-11",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "場所",
          "全国の各道場。オンライン開催の有無も個別確認"
        ],
        [
          "参加",
          "対象年齢・持ち物・申込方法は各道場で確認"
        ],
        [
          "費用",
          "参加先の案内で確認。交通費・機器も考慮"
        ]
      ],
      "keywords": [
        "マイクラ",
        "マインクラフト",
        "ゲーム"
      ],
      "reason": "ScratchやWeb制作など、興味に合わせて取り組む地域の活動です。扱う内容は道場ごとに違います。",
      "step": "近くの道場を1つ選び、開催案内を確認する。",
      "conceptIds": [
        "making-things"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "make"
      ]
    },
    "guitar-anatomy": {
      "domain": "sound",
      "domains": [
        "sound",
        "design"
      ],
      "group": "try",
      "kind": "自宅・読みもの",
      "type": "resource",
      "name": "ギターの音色は、どこで変わる？",
      "summary": "ピックアップやエフェクター、木材と楽器の仕組みを図から知る。",
      "url": "https://www.yamaha.com/ja/musical_instrument_guide/electric_guitar/",
      "source": "ヤマハ 楽器解体全書",
      "checkedOn": "2026-09-11",
      "example": false,
      "online": true,
      "free": true,
      "conditions": [
        [
          "形式",
          "Web記事。読むだけでも利用できます"
        ],
        [
          "費用",
          "記事の閲覧は無料"
        ],
        [
          "内容",
          "仕組み・奏法・製作など。学問への接続は本アプリの編集です"
        ]
      ],
      "reason": "音の仕組みと、楽器の形・材料を同じ対象から見られます。音響とデザインをつなぐ読みものです。",
      "step": "「しくみ」から気になる見出しを選ぶ。楽器の購入は不要。",
      "conceptIds": [
        "making-things",
        "sound-science"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "dig"
      ]
    },
    "fermentation": {
      "domain": "food",
      "domains": [
        "food",
        "ecology"
      ],
      "group": "try",
      "kind": "自宅・読みもの",
      "type": "resource",
      "name": "身近な調味料と「発酵」の不思議",
      "summary": "味噌や醤油など、発酵食品を支える微生物の働きを知る。",
      "url": "https://www.maff.go.jp/j/pr/aff/2211/spe1_01.html",
      "source": "農林水産省",
      "checkedOn": "2026-09-11",
      "example": false,
      "online": true,
      "free": true,
      "conditions": [
        [
          "形式",
          "Web記事・2022年11月号"
        ],
        [
          "費用",
          "記事の閲覧は無料"
        ],
        [
          "活動",
          "読む・比べる提案です。発酵実験の手順ではありません"
        ]
      ],
      "reason": "料理に使う食品を、微生物と成分の変化から見る入口です。好きな料理から科学の問いを見つけられます。",
      "step": "家で使う調味料を1つ思い浮かべて、記事に登場するか探す。",
      "conceptIds": [
        "microbe-life"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "dig"
      ]
    },
    "oshima-school": {
      "domain": "ecology",
      "domains": [
        "ecology"
      ],
      "group": "study",
      "kind": "高校・進学",
      "type": "school",
      "name": "大島海洋国際高校",
      "summary": "海と関わる学校生活や、潜水部などの活動から高校を知る。",
      "url": "https://www.metro.ed.jp/oosimakaiyokokusai-h/index.html",
      "source": "東京都立大島海洋国際高等学校",
      "checkedOn": "2026-09-11",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "地域",
          "東京都・伊豆大島"
        ],
        [
          "生活",
          "寄宿舎・通学条件を学校案内で確認"
        ],
        [
          "入学",
          "応募資格・学費・選抜方法は最新の入試案内へ"
        ]
      ],
      "child": "oshima-diving",
      "reason": "海への興味を、授業だけでなく学校生活や部活動から考える入口。生態学を専門的に学べると保証するものではありません。",
      "conceptIds": [
        "marine-life",
        "fieldwork"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": []
    },
    "oshima-diving": {
      "domain": "ecology",
      "domains": [
        "ecology"
      ],
      "group": "continue",
      "kind": "校内・部活動",
      "type": "club",
      "name": "大島海洋国際高校の潜水部",
      "summary": "器材の扱いや浮力コントロールなど、活動報告から海との関わりを知る。",
      "url": "https://www.metro.ed.jp/oosimakaiyokokusai-h/activities/2026/08/29_3.html",
      "source": "東京都立大島海洋国際高等学校",
      "checkedOn": "2026-09-11",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "所属",
          "同校の部活動。在校生の活動報告"
        ],
        [
          "内容",
          "2026年8月の大会報告"
        ],
        [
          "参加",
          "活動日・入部条件・費用は学校へ確認"
        ]
      ],
      "host": "oshima-school",
      "reason": "海への関心を実技の面から広げる活動例です。生物調査そのものを行うという意味ではありません。",
      "conceptIds": [
        "marine-life",
        "fieldwork"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "observe"
      ]
    },
    "oshima-visit": {
      "domain": "ecology",
      "domains": [
        "ecology"
      ],
      "group": "try",
      "kind": "イベント",
      "type": "event",
      "name": "学校説明会・部活動体験（大島）",
      "summary": "学校説明会と体験入部。午前・午後の片方のみの参加も案内されています。",
      "url": "https://www.metro.ed.jp/oosimakaiyokokusai-h/news/2026/08/6_7_27_1_1_1_1_1.html",
      "source": "東京都立大島海洋国際高等学校",
      "checkedOn": "2026-09-11",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "日程",
          "2026年10月24日（土）"
        ],
        [
          "場所",
          "東京都・伊豆大島"
        ],
        [
          "参加",
          "対象・定員・締切は実施要項と申込ページで確認"
        ],
        [
          "手続",
          "同意書への同意が必要。交通・宿泊費なども確認"
        ]
      ],
      "host": "oshima-school",
      "date": "2026-10-24",
      "reason": "実際の学校や活動を見て、続けたいか確かめる入口。体験参加と入学資格は別です。",
      "conceptIds": [
        "marine-life"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "observe"
      ]
    },
    "kaiyo-life": {
      "domain": "food",
      "domains": [
        "food",
        "ecology"
      ],
      "group": "study",
      "kind": "大学・進学",
      "type": "university",
      "name": "東京海洋大学 海洋生命科学部",
      "summary": "海洋生物資源・食品生産・海洋政策文化という複数の切り口を知る。",
      "url": "https://www.kaiyodai.ac.jp/faculty/s/",
      "source": "東京海洋大学",
      "checkedOn": "2026-09-11",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "地域",
          "東京都・品川キャンパス"
        ],
        [
          "内容",
          "学部・学科紹介。進学先の一例"
        ],
        [
          "入学",
          "科目・費用・出願条件は最新の入試案内へ"
        ]
      ],
      "reason": "海洋生物と食品を同じ学部の中で扱います。料理が好きという入口から、食品を研究する進路にもつながります。",
      "conceptIds": [
        "marine-life",
        "biology"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": []
    },
    "kaiyo-engineering": {
      "domain": "engineering",
      "domains": [
        "engineering"
      ],
      "group": "study",
      "kind": "大学・進学",
      "type": "university",
      "name": "東京海洋大学 海洋工学部",
      "summary": "船舶・電子機械・流通情報など、海の技術を扱う学科を知る。",
      "url": "https://www.kaiyodai.ac.jp/faculty/e/",
      "source": "東京海洋大学",
      "checkedOn": "2026-09-11",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "地域",
          "東京都・越中島キャンパス"
        ],
        [
          "内容",
          "学部・学科紹介"
        ],
        [
          "入学",
          "科目・費用・出願条件は最新の入試案内へ"
        ]
      ],
      "reason": "海で使う機械だけでなく、情報や物流という仕組みにも目を向ける進路です。",
      "conceptIds": [
        "marine-life"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": []
    },
    "kaiyo-environment": {
      "domain": "environment",
      "domains": [
        "environment"
      ],
      "group": "study",
      "kind": "大学・進学",
      "type": "university",
      "name": "東京海洋大学 海洋資源環境学部",
      "summary": "海洋環境と資源・エネルギーの観点から学びを知る。",
      "url": "https://www.kaiyodai.ac.jp/faculty/r/",
      "source": "東京海洋大学",
      "checkedOn": "2026-09-11",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "地域",
          "東京都・品川キャンパス"
        ],
        [
          "内容",
          "学部・学科紹介"
        ],
        [
          "入学",
          "科目・費用・出願条件は最新の入試案内へ"
        ]
      ],
      "reason": "環境を理解する学びと、資源をどう扱うかという問いを比較できます。",
      "conceptIds": [
        "marine-life",
        "environment-living"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": []
    },
    "ritsumeikan-media": {
      "domain": "media",
      "domains": [
        "media",
        "information",
        "design"
      ],
      "group": "study",
      "kind": "大学・進学",
      "type": "university",
      "name": "立命館大学 映像学部",
      "summary": "映画・ゲーム・技術・マネジメントなど、映像をめぐる学びを知る。",
      "url": "https://admission.ritsumei.ac.jp/faculty/cias.html",
      "source": "立命館大学",
      "checkedOn": "2026-09-11",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "地域",
          "大阪府・大阪いばらきキャンパス"
        ],
        [
          "内容",
          "学部の5つの学びのゾーンを紹介"
        ],
        [
          "入学",
          "科目・費用・出願条件は最新の入試案内へ"
        ]
      ],
      "reason": "ゲームはプログラミングだけではありません。作品表現や社会との関わりも含む学びを比較できます。",
      "conceptIds": [],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": []
    },
    "kyushu-sound": {
      "domain": "sound",
      "domains": [
        "sound",
        "design"
      ],
      "group": "study",
      "kind": "大学・進学",
      "type": "university",
      "name": "九州大学 芸術工学部 音響設計コース",
      "summary": "音文化・音響環境・音響情報を横断して学ぶコース。",
      "url": "https://www.design.kyushu-u.ac.jp/schools/ad/",
      "source": "九州大学",
      "checkedOn": "2026-09-11",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "地域",
          "福岡県"
        ],
        [
          "内容",
          "コースのカリキュラムと学ぶ分野"
        ],
        [
          "入学",
          "科目・費用・出願条件は最新の入試案内へ"
        ]
      ],
      "reason": "音楽への興味を、文化だけでなく物理や聴覚、情報の視点からも深められます。",
      "conceptIds": [
        "sound-science"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": []
    },
    "ikilog": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "environment",
        "information"
      ],
      "group": "try",
      "kind": "自宅・記録",
      "type": "resource",
      "name": "見つけた生きものを記録する",
      "summary": "全国の観察記録を種名から調べられる。自分が見つけた生き物も登録して残せる。",
      "url": "https://ikilog.biodic.go.jp/",
      "source": "環境省生物多様性センター",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": true,
      "free": false,
      "conditions": [
        [
          "対象",
          "年齢の条件はサイト内に記載がありません"
        ],
        [
          "費用",
          "利用料の記載を公式ページで確認できていません"
        ],
        [
          "利用",
          "閲覧は誰でもできる。報告や調査への参加にはユーザ登録が必要"
        ],
        [
          "場所",
          "オンライン。記録するのは自分で観察した場所"
        ]
      ],
      "reason": "「どこで何が見つかったか」を種名から追えます。海・森・川・街のどこで見つけたものも、同じ形で記録できます。",
      "step": "知っている生き物の名前を1つ入れて、近くに記録があるか見る。",
      "conceptIds": [
        "citizen-survey",
        "record-keeping",
        "urban-nature"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "observe"
      ]
    },
    "kahaku-vr": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "media"
      ],
      "group": "try",
      "kind": "自宅・教材",
      "type": "resource",
      "name": "博物館の展示を家から歩く",
      "summary": "国立科学博物館の展示室を3Dビューで見て回れる。筑波実験植物園も含む。",
      "url": "https://www.kahaku.go.jp/VR/",
      "source": "国立科学博物館",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": true,
      "free": true,
      "conditions": [
        [
          "対象",
          "年齢の指定はなし。VRゴーグルを使う場合は機器の使用条件を確認"
        ],
        [
          "費用",
          "無料（通信料は自己負担）"
        ],
        [
          "場所",
          "オンライン。PC・スマートフォンで閲覧できる"
        ],
        [
          "内容",
          "日本館・地球館・企画展・筑波実験植物園の3Dビュー"
        ]
      ],
      "reason": "実物の標本がどう並んでいるかを先に見ておくと、現地へ行ったとき何を見たいかが決まります。",
      "step": "地球館の1フロアだけ回って、気になった展示の名前を控える。",
      "conceptIds": [
        "biology",
        "plant-life"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "observe"
      ]
    },
    "wbsj-startbird": {
      "domain": "ecology",
      "domains": [
        "ecology"
      ],
      "group": "try",
      "kind": "自宅・教材",
      "type": "resource",
      "name": "鳥の見分け方を知る",
      "summary": "道具の選び方、探し方、身近な鳥と季節の鳥の見分け方、観察のマナー。",
      "url": "https://www.wbsj.org/activity/spread-and-education/bbw/",
      "source": "公益財団法人 日本野鳥の会",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": true,
      "free": true,
      "conditions": [
        [
          "対象",
          "初心者向け。年齢の指定はありません"
        ],
        [
          "費用",
          "ページの閲覧は無料。冊子や双眼鏡は別"
        ],
        [
          "場所",
          "オンラインで読み、観察は家の窓や近所から"
        ],
        [
          "内容",
          "道具・探し方・見分け方・フィールドマナー"
        ]
      ],
      "reason": "鳥は街でも海でも森でも見られます。見分け方を先に知っておくと、どこへ行っても同じ目で見られます。",
      "step": "窓から見える鳥を1種類だけ、名前まで調べてみる。",
      "conceptIds": [
        "bird-life",
        "fieldwork",
        "urban-nature"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "observe",
        "compare"
      ]
    },
    "nacsj-shizenshirabe": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "environment"
      ],
      "group": "try",
      "kind": "自宅・教材",
      "type": "resource",
      "name": "身近な生きものの見分け方マニュアル",
      "summary": "市民参加の調査「自然しらべ」で使われた、カメ・アリ・セミ・貝殻などの資料。",
      "url": "https://www.nacsj.or.jp/activities/ss/",
      "source": "公益財団法人 日本自然保護協会",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": true,
      "free": true,
      "conditions": [
        [
          "対象",
          "子どもから大人まで。年齢の指定はありません"
        ],
        [
          "費用",
          "過去の実施分のマニュアルを無料で公開"
        ],
        [
          "時期",
          "掲載されている最新の調査は2023年のカメ一斉調査。現在の募集は公式ページで確認"
        ],
        [
          "場所",
          "オンラインで読み、観察は身近な場所で"
        ]
      ],
      "reason": "テーマごとに「どこを見れば見分けられるか」が書かれています。虫・貝・水辺と、対象を変えて同じ観察ができます。",
      "step": "気になるテーマを1つ開き、見分けるポイントを3つ書き出す。",
      "conceptIds": [
        "citizen-survey",
        "insect-life",
        "urban-nature",
        "freshwater-life",
        "ecology-links"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "compare",
        "observe"
      ]
    },
    "omnh-ouchi": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "media"
      ],
      "group": "try",
      "kind": "自宅・教材",
      "type": "resource",
      "name": "学芸員の解説を家で見る",
      "summary": "標本の話、展示の解説動画、近所で観察するための読みものを公開している。",
      "url": "https://www.omnh.jp/ouchi/index.html",
      "source": "大阪市立自然史博物館",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": true,
      "free": true,
      "conditions": [
        [
          "対象",
          "子ども向けから大人向けまで。年齢の指定はありません"
        ],
        [
          "費用",
          "無料"
        ],
        [
          "場所",
          "オンライン"
        ],
        [
          "内容",
          "標本解説の動画、ギャラリートーク、3Dモデル、近所での観察の読みもの"
        ]
      ],
      "reason": "博物館の人がどこを見て種類を判断しているかがわかります。自分で拾ったものの扱い方にもつながります。",
      "step": "「ごきんじょでかんさつに出かけよう」を読んで、近所で1つ探してみる。",
      "conceptIds": [
        "biology",
        "record-keeping",
        "urban-nature"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "dig"
      ]
    },
    "maff-kids": {
      "domain": "food",
      "domains": [
        "food",
        "ecology",
        "environment"
      ],
      "group": "try",
      "kind": "自宅・教材",
      "type": "resource",
      "name": "森・海・畑のしくみを読む",
      "summary": "林業・水産業・農産物のしくみを、読みものやクイズで知る。",
      "url": "https://www.maff.go.jp/j/kids/",
      "source": "農林水産省",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": true,
      "free": true,
      "conditions": [
        [
          "対象",
          "こども向け。学年の指定はありません"
        ],
        [
          "費用",
          "無料"
        ],
        [
          "場所",
          "オンライン"
        ],
        [
          "内容",
          "「森林を知りたい」「水産業を知りたい」「農産物博士になろう」など"
        ]
      ],
      "reason": "生き物を食べものや産業の側から見ると、森・海・畑が同じ話としてつながります。",
      "step": "「森林を知りたい」を開いて、木が育つまでの年数を確かめる。",
      "conceptIds": [
        "forest-life",
        "marine-life",
        "environment-living"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "dig"
      ]
    },
    "shizen-kyoikuen": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "environment"
      ],
      "group": "try",
      "kind": "自然観察施設",
      "type": "resource",
      "name": "国立科学博物館附属自然教育園",
      "summary": "都心に残された森・草地・水辺を、手を入れすぎない状態で保っている。",
      "url": "https://ins.kahaku.go.jp/",
      "source": "国立科学博物館",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": true,
      "conditions": [
        [
          "場所",
          "東京都港区白金台"
        ],
        [
          "費用",
          "高校生以下は無料。大人320円（交通費は別）"
        ],
        [
          "時間",
          "9:00〜16:30（入園は16:00まで）"
        ],
        [
          "内容",
          "園内の開花情報、展示、イベントの案内がある"
        ]
      ],
      "reason": "街の真ん中にも森と水辺があります。遠くへ行かなくても、森・草地・池の違いを一度に見比べられます。",
      "step": "入口でその日の開花・観察情報を見てから歩く。",
      "conceptIds": [
        "urban-nature",
        "fieldwork",
        "plant-life",
        "forest-life"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "observe"
      ]
    },
    "tsukuba-botanical": {
      "domain": "ecology",
      "domains": [
        "ecology"
      ],
      "group": "try",
      "kind": "自然観察施設",
      "type": "resource",
      "name": "筑波実験植物園",
      "summary": "さまざまな環境に育つ植物を、区画に分けて植えている研究機関の植物園。",
      "url": "https://tbg.kahaku.go.jp/",
      "source": "国立科学博物館",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": true,
      "conditions": [
        [
          "場所",
          "茨城県つくば市（国立科学博物館の研究施設）"
        ],
        [
          "費用",
          "小・中・高校生と65歳以上は無料。一般・大学生320円"
        ],
        [
          "時間",
          "9:00〜16:30（入園は16:00まで）。月曜休園（祝日は開園）"
        ],
        [
          "内容",
          "屋外の「世界の生態区」「生命を支える多様区」と温室"
        ]
      ],
      "reason": "同じ「植物」でも、育つ環境ごとに姿が違うことを、歩いて比べられます。",
      "step": "温室と屋外で、葉の厚さや形がどう違うか見比べる。",
      "conceptIds": [
        "plant-life",
        "fieldwork",
        "biology"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "observe"
      ]
    },
    "biwahaku": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "environment"
      ],
      "group": "try",
      "kind": "博物館・水族展示",
      "type": "resource",
      "name": "滋賀県立琵琶湖博物館",
      "summary": "琵琶湖の成り立ちと今を扱う博物館。国内最大級の淡水生物の水族展示がある。",
      "url": "https://www.biwahaku.jp/",
      "source": "滋賀県立琵琶湖博物館",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": true,
      "conditions": [
        [
          "場所",
          "滋賀県草津市下物町"
        ],
        [
          "費用",
          "常設展示は高校生・18歳未満・中学生以下が無料。企画展は高校生・18歳未満270円"
        ],
        [
          "時間",
          "9:30〜17:00（最終入館16:00）。月曜休館（祝日は開館）"
        ],
        [
          "内容",
          "琵琶湖の淡水生物の水族展示。観察会などのイベントもある"
        ]
      ],
      "reason": "海の魚とは違う、川と湖の生き物だけを集めた展示です。淡水という切り口で生き物を見直せます。",
      "step": "水族展示で、同じ魚が湖と川のどちらにいるか確かめる。",
      "conceptIds": [
        "freshwater-life",
        "biology",
        "fieldwork",
        "ecology-links"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "observe"
      ]
    },
    "chiba-umihaku": {
      "domain": "ecology",
      "domains": [
        "ecology"
      ],
      "group": "try",
      "kind": "博物館",
      "type": "resource",
      "name": "千葉県立中央博物館分館 海の博物館",
      "summary": "房総の海と自然をテーマにした自然史博物館。海岸のすぐそばにある。",
      "url": "https://www.chiba-muse.or.jp/UMIHAKU/",
      "source": "千葉県立中央博物館分館 海の博物館",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "場所",
          "千葉県勝浦市吉尾"
        ],
        [
          "費用",
          "高校生・大学生100円、一般200円、中学生以下と65歳以上は無料"
        ],
        [
          "時間",
          "9:00〜16:30（入館は16:00まで）。月曜休館"
        ],
        [
          "内容",
          "房総の海の生き物の常設展示と企画展示"
        ]
      ],
      "reason": "水族館とは別に、標本から海の生き物を見る場所です。近くの海岸で観察会も開かれています。",
      "step": "展示で見た生き物が、近くの海岸のどこにいるか確かめる。",
      "conceptIds": [
        "marine-life",
        "biology",
        "fieldwork"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "observe"
      ]
    },
    "umihaku-kansatsu": {
      "domain": "ecology",
      "domains": [
        "ecology"
      ],
      "group": "try",
      "kind": "観察会の案内",
      "type": "resource",
      "name": "海の博物館の観察会",
      "summary": "研究員が案内する、磯の生き物・貝殻・海藻・海鳥などの観察会の一覧。",
      "url": "https://www.chiba-muse.or.jp/UMIHAKU/event/category/kansatu/",
      "source": "千葉県立中央博物館分館 海の博物館",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "対象",
          "回によって異なる。小学校4年生以上と案内されている回がある"
        ],
        [
          "費用",
          "回ごとに異なるため、各回のページで確認"
        ],
        [
          "申込",
          "事前申込が必要"
        ],
        [
          "時期",
          "「砂浜で貝殻を探そう」2026年10月10日、「鵜原理想郷 秋の生きもの探し」2026年11月1日、「ウのねぐら鵜ォッチング」2026年12月12日など"
        ],
        [
          "場所",
          "勝浦市内の海岸など、回ごとに集合場所が異なる"
        ]
      ],
      "host": "chiba-umihaku",
      "reason": "一人では見つけられない生き物を、研究している人と一緒に探せます。同じ海岸でも季節ごとにテーマが変わります。",
      "step": "一覧から行ける日の回を選び、対象と申込の締切を確認する。",
      "conceptIds": [
        "marine-life",
        "fieldwork",
        "citizen-survey"
      ],
      "reviewStatus": "published",
      "reviewAfter": "2026-11-02",
      "verbs": [
        "observe"
      ]
    },
    "hirameki-science": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "environment",
        "information"
      ],
      "group": "try",
      "kind": "大学の体験プログラム",
      "type": "resource",
      "name": "ひらめき☆ときめきサイエンス",
      "summary": "大学や研究機関が、進行中の研究を中高生向けの講義・実験として公開する。",
      "url": "https://www.jsps.go.jp/hirameki/",
      "source": "独立行政法人 日本学術振興会",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "対象",
          "小学5・6年生、中学生、高校生"
        ],
        [
          "費用",
          "プログラムごとに異なるため、各プログラムの概要で確認"
        ],
        [
          "申込",
          "各プログラムの概要に書かれた実施機関へ直接申し込む。日本学術振興会は申込を受け付けていない"
        ],
        [
          "場所",
          "実施する大学・研究機関ごと。全国で開催"
        ],
        [
          "時期",
          "年度ごとに実施プログラム一覧が公開される"
        ]
      ],
      "reason": "大学の研究室で実際に何をしているかを、進学前に一度見られます。学部の名前だけではわからない中身がわかります。",
      "step": "実施プログラム一覧で、自分が行ける場所のものを探す。",
      "conceptIds": [
        "research-challenge",
        "biology",
        "fieldwork"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "dig"
      ]
    },
    "hokudai-coast-ecology": {
      "domain": "ecology",
      "domains": [
        "ecology"
      ],
      "group": "try",
      "kind": "イベント",
      "type": "event",
      "name": "海岸動物の行動生態学入門（北海道大学）",
      "summary": "海岸で動物を観察・採集し、実習室で行動の実験を体験する。研究施設の紹介つき。",
      "url": "https://www2.fish.hokudai.ac.jp/event/29160/",
      "source": "北海道大学 大学院水産科学研究院",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": true,
      "conditions": [
        [
          "対象",
          "中学生・高校生（保護者の同伴も歓迎）"
        ],
        [
          "費用",
          "参加費は無料（交通費は別）"
        ],
        [
          "定員",
          "15名"
        ],
        [
          "申込",
          "2026年10月1日〜2027年3月1日。申込先は公式案内のリンクから"
        ],
        [
          "場所",
          "北海道函館市・北海道大学水産学部"
        ],
        [
          "注意",
          "2026年8月1日の回は終了。掲載は2026年5月1日更新のため、最新の実施状況を確認"
        ]
      ],
      "host": "hokudai-fisheries",
      "date": "2027-03-21",
      "reason": "ひらめき☆ときめきサイエンスの実例です。海の生き物を「行動」から調べる方法を、研究している場所で体験できます。",
      "step": "申込開始日を控えて、募集ページを確認する。",
      "conceptIds": [
        "marine-life",
        "fieldwork",
        "research-challenge"
      ],
      "reviewStatus": "published",
      "reviewAfter": "2027-03-22",
      "verbs": [
        "dig"
      ]
    },
    "hiroshima-kokai": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "environment"
      ],
      "group": "try",
      "kind": "大学の公開講座",
      "type": "resource",
      "name": "広島大学 高校生対象公開講座",
      "summary": "DNAと植物、両生類の研究、オオサンショウウオの保護、宮島の植物と自然など。",
      "url": "https://www.hiroshima-u.ac.jp/AC/kokai/31_koza",
      "source": "広島大学",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": true,
      "conditions": [
        [
          "対象",
          "高校生"
        ],
        [
          "費用",
          "受講料は無料"
        ],
        [
          "定員",
          "講座により8〜130名"
        ],
        [
          "時期",
          "2026年度は7月20日〜11月28日に開講"
        ],
        [
          "申込",
          "大学の申込案内に従う"
        ],
        [
          "場所",
          "広島大学の各キャンパスなど"
        ]
      ],
      "reason": "生物・環境の講座が複数あります。大学の先生がどんな問いを立てているかを、一日で確かめられます。",
      "step": "講座一覧から生き物に関わるものを探し、開催日と申込方法を確認する。",
      "conceptIds": [
        "biology",
        "research-challenge",
        "plant-life"
      ],
      "reviewStatus": "published",
      "reviewAfter": "2026-11-29",
      "verbs": [
        "dig"
      ]
    },
    "wbsj-tanchokai": {
      "domain": "ecology",
      "domains": [
        "ecology"
      ],
      "group": "continue",
      "kind": "地域の観察会",
      "type": "community",
      "name": "日本野鳥の会の探鳥会",
      "summary": "各地の支部が開く野鳥観察会。全国で年間およそ3千回開かれている。",
      "url": "https://www.wbsj.org/about-us/group/tanchokai/",
      "source": "公益財団法人 日本野鳥の会",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "対象",
          "会員でなくても参加できる"
        ],
        [
          "費用",
          "参加費は支部・回ごとに異なるため、各支部の案内で確認"
        ],
        [
          "申込",
          "各支部の案内で確認"
        ],
        [
          "場所",
          "北海道から九州・沖縄まで、7ブロックの支部が開催"
        ],
        [
          "その他",
          "掲載されている探鳥会には行事保険がかけられている"
        ]
      ],
      "reason": "同じ場所に毎月通う会もあります。季節で入れかわる鳥を、続けて見ることで違いがわかります。",
      "step": "住んでいる地域の支部を探し、次回の開催日を見る。",
      "conceptIds": [
        "bird-life",
        "fieldwork",
        "citizen-survey"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "observe"
      ]
    },
    "kodomo-ecoclub": {
      "domain": "environment",
      "domains": [
        "environment",
        "ecology"
      ],
      "group": "continue",
      "kind": "継続活動",
      "type": "community",
      "name": "こどもエコクラブ",
      "summary": "地域で環境活動を続けるクラブの登録制度。活動の報告を全国で共有する。",
      "url": "https://www.j-ecoclub.jp/",
      "source": "公益財団法人 日本環境協会",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "対象",
          "3歳から高校生まで"
        ],
        [
          "費用",
          "参加費の記載を公式ページで確認できていません"
        ],
        [
          "申込",
          "サイトからクラブを登録する"
        ],
        [
          "活動",
          "生き物の観察、河川調査、ビオトープ、農作物の研究など、クラブごとに異なる"
        ],
        [
          "場所",
          "各地域。活動場所はクラブごと"
        ]
      ],
      "reason": "一度の体験ではなく、同じ場所を続けて見る活動です。自分で決めたテーマを一年通して調べられます。",
      "step": "ほかのクラブの活動報告を読んで、自分にもできそうなテーマを探す。",
      "conceptIds": [
        "citizen-survey",
        "environment-living",
        "record-keeping"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "observe"
      ]
    },
    "zenkoku-suisei": {
      "domain": "environment",
      "domains": [
        "environment",
        "ecology"
      ],
      "group": "continue",
      "kind": "市民参加の調査",
      "type": "community",
      "name": "全国水生生物調査",
      "summary": "川の石の下の生き物を採って、水のきれいさを4段階で判定する全国調査。",
      "url": "https://water-pub.env.go.jp/water-pub/mizu-site/mizu/suisei/",
      "source": "環境省・国土交通省",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "対象",
          "個人・学校・団体。年齢の制限はなく、子どもも参加できる"
        ],
        [
          "費用",
          "参加費の記載を公式ページで確認できていません"
        ],
        [
          "申込",
          "各都道府県の環境部局へ。一級河川の直轄管理区間は各地方整備局の窓口へ"
        ],
        [
          "時期",
          "4月〜10月。夏休み期間が中心"
        ],
        [
          "内容",
          "29種の指標生物から、水質を4階級（きれいな水〜とてもきたない水）で判定"
        ]
      ],
      "reason": "同じ方法で全国の人が調べているので、自分の川の結果をほかの場所と比べられます。",
      "step": "住んでいる都道府県の窓口を調べ、近くの川の結果が出ているか見る。",
      "conceptIds": [
        "freshwater-life",
        "citizen-survey",
        "fieldwork",
        "ecology-links"
      ],
      "reviewStatus": "published",
      "reviewAfter": "2027-04-01",
      "verbs": [
        "observe"
      ]
    },
    "takao-satoyama": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "environment"
      ],
      "group": "continue",
      "kind": "継続活動",
      "type": "community",
      "name": "高尾の森自然学校の里山保全",
      "summary": "ナラ枯れした木の伐採、苗木の植樹、トンボ池の整備などを続けて行う。",
      "url": "https://www.7midori.org/takao/volunteer/",
      "source": "一般財団法人セブン-イレブン記念財団",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "対象",
          "里山保全活動は中学生以上（小学生以下は要相談）。小学3年〜中学3年向けのジュニアボランティアもある"
        ],
        [
          "費用",
          "参加費の記載を公式ページで確認できていません"
        ],
        [
          "日程",
          "里山保全は月3回程度（8月を除く）9:30〜14:30。午前のみの参加も可"
        ],
        [
          "場所",
          "東京都八王子市川町"
        ],
        [
          "申込",
          "活動ごとにフォームまたはメール"
        ]
      ],
      "reason": "観察するだけでなく、人が手を入れることで保たれる森があります。手入れの前と後で生き物がどう変わるかを見られます。",
      "step": "次の活動日を確認し、午前だけ参加できるか問い合わせる。",
      "conceptIds": [
        "forest-care",
        "forest-life",
        "fieldwork",
        "plant-life"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "make"
      ]
    },
    "satoyama-go": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "environment"
      ],
      "group": "continue",
      "kind": "継続活動",
      "type": "community",
      "name": "里山へGO！（東京都の保全地域）",
      "summary": "東京都の保全地域で、自然観察・森の手入れ・田んぼの活動などに参加できる。",
      "url": "https://satoyama.tokyo-biodiversity.metro.tokyo.lg.jp/",
      "source": "東京都（公益財団法人東京都環境公社が運営）",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "対象",
          "回ごとに異なる。中学生・高校生・学生を対象にした回がある（2026年9月19日・宇津木緑地保全地域、定員30名の先着）"
        ],
        [
          "費用",
          "参加費の記載を公式ページで確認できていません"
        ],
        [
          "申込",
          "イベントごとに申し込む。会員登録が必要"
        ],
        [
          "場所",
          "東京都多摩地域の保全地域（横沢入、長房緑地、宇津木緑地など）"
        ],
        [
          "活動",
          "自然観察、森の手入れ、栗ひろい、稲刈りなど"
        ]
      ],
      "reason": "都内にも、続けて通える里山があります。季節ごとに作業が変わるので、一年を通して同じ場所を見られます。",
      "step": "活動スケジュールから、中高生も参加できる回を探す。",
      "conceptIds": [
        "forest-care",
        "fieldwork",
        "urban-nature"
      ],
      "reviewStatus": "published",
      "reviewAfter": "2026-12-01",
      "verbs": [
        "make"
      ]
    },
    "marine-challenge": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "environment"
      ],
      "group": "continue",
      "kind": "研究への挑戦（次回募集待ち）",
      "type": "resource",
      "name": "マリンチャレンジプログラム",
      "summary": "海・水産・水環境の研究に取り組む10代に、研究費と研究者のサポートをつける。",
      "url": "https://marinechallenge.lne.st/outline/",
      "source": "日本財団・JASTO・株式会社リバネス",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "対象",
          "10代の個人またはチーム。大学生・高専生は研究室に所属していない人"
        ],
        [
          "費用",
          "採択されると研究費5万円。地方大会の交通費補助あり"
        ],
        [
          "募集",
          "2026年度の応募は2026年2月27日で締切済み。次回の募集は公式ページで確認"
        ],
        [
          "流れ",
          "書類審査とオンライン面談 → 地方大会 → 全国大会"
        ],
        [
          "場所",
          "全国5ブロック"
        ]
      ],
      "reason": "観察や記録を「自分の研究」にしたいときの受け皿です。今年の募集は終わっていますが、何が求められるかを先に読めます。",
      "step": "これまで採択された研究のテーマを見て、自分の問いに近いものを探す。",
      "conceptIds": [
        "research-challenge",
        "marine-life",
        "record-keeping"
      ],
      "reviewStatus": "published",
      "reviewAfter": "2026-12-01",
      "verbs": [
        "dig"
      ]
    },
    "kikigaki": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "environment",
        "media"
      ],
      "group": "continue",
      "kind": "高校生の活動（次回募集待ち）",
      "type": "resource",
      "name": "聞き書き甲子園",
      "summary": "森・川・海とともに生きる「名人」を訪ね、話を聞いて記録し、作品にする。",
      "url": "https://www.kikigaki.net/entry",
      "source": "聞き書き甲子園実行委員会",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": true,
      "conditions": [
        [
          "対象",
          "高校生"
        ],
        [
          "費用",
          "参加費は無料"
        ],
        [
          "定員",
          "65名"
        ],
        [
          "募集",
          "第25回の応募は2026年6月25日必着で終了。次回の募集は公式ページで確認"
        ],
        [
          "活動",
          "事前研修に参加し、9月〜11月に名人を取材、作品を提出する"
        ],
        [
          "注意",
          "長距離の移動と団体での宿泊をともなう"
        ]
      ],
      "reason": "生き物そのものではなく、そこで暮らしてきた人から森や海を知る方法です。記録して伝えるところまでが活動に入っています。",
      "step": "過去の作品を1つ読んで、どんな聞き方をしているか見る。",
      "conceptIds": [
        "forest-life",
        "marine-life",
        "record-keeping"
      ],
      "reviewStatus": "published",
      "reviewAfter": "2027-05-01",
      "verbs": [
        "tell"
      ]
    },
    "tuat-ecoregion": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "environment"
      ],
      "group": "study",
      "kind": "大学・進学",
      "type": "university",
      "name": "東京農工大学 農学部 地域生態システム学科",
      "summary": "森林・野生動物・環境・地域計画を一つの学科で扱い、実習科目が多い。",
      "url": "https://www.tuat.ac.jp/department/agriculture/region/curriculum.html",
      "source": "東京農工大学",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "場所",
          "東京都府中市（農学部）"
        ],
        [
          "内容",
          "育林学実習、樹木学実習、野生動物保全学実習、森林土壌学実験・実習、山地保全・砂防計画学実習などが正規の科目"
        ],
        [
          "対象",
          "在学生向けの授業。中高生が参加できる活動ではありません"
        ],
        [
          "入学",
          "科目・費用・出願条件は公式の入試案内で確認"
        ]
      ],
      "reason": "「森が好き」から進める学科の一つです。講義だけでなく実習が組まれていることが、カリキュラムから確認できます。",
      "conceptIds": [
        "forest-life",
        "fieldwork",
        "ecology-links"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": []
    },
    "hokudai-fisheries": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "food",
        "engineering"
      ],
      "group": "study",
      "kind": "大学・進学",
      "type": "university",
      "name": "北海道大学 水産学部",
      "summary": "海洋生物・海洋資源・増殖生命・資源機能化学の4学科。附属の練習船を持つ。",
      "url": "https://www2.fish.hokudai.ac.jp/department-graduate-school/school-of-fisheries-sciences.html",
      "source": "北海道大学 大学院水産科学研究院",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "場所",
          "1〜2年は札幌キャンパス、3年から函館キャンパス"
        ],
        [
          "学科",
          "海洋生物科学科／海洋資源科学科／増殖生命科学科／資源機能化学科"
        ],
        [
          "施設",
          "附属練習船「おしょろ丸」「うしお丸」"
        ],
        [
          "注意",
          "乗船実習がどの科目で必修かは、公式のシラバスで確認"
        ],
        [
          "入学",
          "科目・費用・出願条件は公式の入試案内で確認"
        ]
      ],
      "reason": "海の生き物を、資源・食品・環境のどこから見るかで学科が分かれています。同じ「海」でも進む先が違います。",
      "conceptIds": [
        "marine-life",
        "fieldwork",
        "biology"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": []
    },
    "mie-bioresources": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "environment",
        "food"
      ],
      "group": "study",
      "kind": "大学・進学",
      "type": "university",
      "name": "三重大学 生物資源学部",
      "summary": "海洋生物資源・農林環境科学・生命化学のコース。演習林・水産実験所・練習船を持つ。",
      "url": "https://www.bio.mie-u.ac.jp/",
      "source": "三重大学 生物資源学部",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "場所",
          "三重県津市"
        ],
        [
          "コース",
          "2年次以降に海洋生物資源学／農林環境科学／生命化学から選ぶ"
        ],
        [
          "施設",
          "附属紀伊・黒潮生命地域フィールドサイエンスセンター（農場・演習林・水産実験所）と練習船「勢水丸」"
        ],
        [
          "対象",
          "在学生向けの教育・研究施設です"
        ],
        [
          "入学",
          "科目・費用・出願条件は公式の入試案内で確認"
        ]
      ],
      "reason": "海と森を別々の学部に分けず、同じ学部の中から選べます。決めきらずに入って、あとから寄せていけます。",
      "conceptIds": [
        "marine-life",
        "forest-life",
        "ecology-links"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": []
    },
    "shinshu-bio": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "environment"
      ],
      "group": "study",
      "kind": "大学・進学",
      "type": "university",
      "name": "信州大学 理学部 生物学コース",
      "summary": "山と湖に囲まれた立地で、生態学実験や臨湖実習などの野外実習がある。",
      "url": "https://www.shinshu-u.ac.jp/faculty/science/bio/overview/post.html",
      "source": "信州大学 理学部",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "場所",
          "長野県松本市（理学部）"
        ],
        [
          "施設",
          "理学部附属 湖沼高地教育研究センター（諏訪臨湖実験所ほか）"
        ],
        [
          "内容",
          "生態学実験、進化生物学実習、臨湖実習などの実習科目。諏訪湖では船からの採水・水質計測・水草の観察を行う"
        ],
        [
          "対象",
          "在学生向けの授業。中高生向けの一般公開は公式ページで確認できていません"
        ],
        [
          "入学",
          "科目・費用・出願条件は公式の入試案内で確認"
        ]
      ],
      "reason": "川や湖の生き物を専門に扱える大学は多くありません。湖の実験所を持っていることが、学べる内容に直結します。",
      "conceptIds": [
        "freshwater-life",
        "fieldwork",
        "biology"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": []
    },
    "gifu-forest-academy": {
      "domain": "ecology",
      "domains": [
        "ecology",
        "engineering",
        "design"
      ],
      "group": "study",
      "kind": "専門学校・進学",
      "type": "school",
      "name": "岐阜県立森林文化アカデミー",
      "summary": "岐阜県が設置する、森林・木材・木造建築・木工の専門学校。",
      "url": "https://www.forest.ac.jp/",
      "source": "岐阜県立森林文化アカデミー",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "場所",
          "岐阜県美濃市"
        ],
        [
          "学科",
          "森と木のエンジニア科（高卒程度が対象）／森と木のクリエーター科（22歳以上が対象）"
        ],
        [
          "内容",
          "林業、林産業、森林環境教育、木造建築、木工"
        ],
        [
          "機会",
          "オープンキャンパスを実施"
        ],
        [
          "入学",
          "出願条件・費用は公式の入学案内で確認"
        ]
      ],
      "reason": "大学以外にも、森を仕事にする学び方があります。木を育てる側と、木を使う側で学科が分かれています。",
      "conceptIds": [
        "forest-life",
        "forest-care",
        "making-things"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": []
    },
    "igusa-bio-club": {
      "domain": "ecology",
      "domains": [
        "ecology"
      ],
      "group": "study",
      "kind": "高校の部活動",
      "type": "club",
      "name": "東京都立井草高等学校 生物部",
      "summary": "部員39名。平日の活動に加えて土日に野外調査を行い、学会でも発表している。",
      "url": "https://www.metro.ed.jp/igusa-h/activities/club_29/index.html",
      "source": "東京都立井草高等学校",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "対象",
          "在校生の部活動。外部の中学生が参加できるかは、このページには書かれていません"
        ],
        [
          "活動",
          "月・水・金。土日に野外活動"
        ],
        [
          "調査地",
          "尾瀬、伊豆大島、奥多摩、三浦半島、御岳山などで合宿・調査"
        ],
        [
          "発表",
          "日本進化学会、日本生物教育会でのポスター発表と部誌の発行"
        ]
      ],
      "reason": "高校でも、学会で発表するところまで続けている部があります。進学より前に、どこまでできるかの一例です。",
      "conceptIds": [
        "fieldwork",
        "biology",
        "record-keeping"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": []
    },
    "omnh": {
      "domain": "ecology",
      "domains": [
        "ecology"
      ],
      "group": "try",
      "kind": "博物館",
      "type": "resource",
      "name": "大阪市立自然史博物館",
      "summary": "大阪の自然と生き物の標本を扱う博物館。観察会や実習の行事、友の会がある。",
      "url": "https://omnh.jp/",
      "source": "大阪市立自然史博物館",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": false,
      "free": false,
      "conditions": [
        [
          "場所",
          "大阪市東住吉区長居公園"
        ],
        [
          "費用",
          "入館料の金額は公式のトップページでは確認できていません。利用案内で確認"
        ],
        [
          "行事",
          "観察会・実習・講演会の一覧と、子ども向けワークショップがある"
        ],
        [
          "続ける",
          "友の会がある（申込は別サイト）"
        ]
      ],
      "reason": "一度見に行くだけでなく、行事や友の会で続けて通えます。標本の見方を教わると、自分で拾ったものも扱えます。",
      "step": "行事の一覧から、参加できそうな観察会を1つ見る。",
      "conceptIds": [
        "insect-life",
        "plant-life",
        "biology"
      ],
      "reviewStatus": "published",
      "reviewAfter": null,
      "verbs": [
        "observe"
      ]
    },
    "u22-procon": {
      "domain": "information",
      "domains": [
        "information",
        "design",
        "media"
      ],
      "group": "continue",
      "kind": "コンテスト（次回募集待ち）",
      "type": "resource",
      "name": "U-22プログラミング・コンテスト",
      "summary": "22歳以下が作ったオリジナル作品を応募するコンテスト。ジャンルや言語の制限はない。",
      "url": "https://u22procon.com/",
      "source": "一般社団法人ソフトウェア協会",
      "checkedOn": "2026-09-12",
      "example": false,
      "online": true,
      "free": false,
      "conditions": [
        [
          "対象",
          "22歳以下、または学生で28歳以下。中高生も応募できる"
        ],
        [
          "費用",
          "応募費用の記載を公式ページで確認できていません"
        ],
        [
          "応募",
          "個人でも団体でも可。これまで応募していないオリジナル作品に限る"
        ],
        [
          "募集",
          "2026年度は7月1日〜8月31日で締切済み。次回の募集は公式ページで確認"
        ],
        [
          "注意",
          "ほかのコンテストとの併願は原則できない"
        ]
      ],
      "reason": "ゲームを作る手を止めずに、外へ出す場所です。作品を説明する形にまとめる練習にもなります。",
      "step": "過去の受賞作品を見て、どこまで作れば出せるか確かめる。",
      "conceptIds": [
        "making-things",
        "research-challenge"
      ],
      "reviewStatus": "published",
      "reviewAfter": "2027-06-01",
      "verbs": [
        "make"
      ]
    }
  }
};
