import {readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const fields=new Set(['ecology','environment','engineering','information','design','food','sound','media']);
const fail=message=>{throw new Error(`Knowledge: ${message}`);};
const text=(value,label,max=1500)=>{if(typeof value!=='string' || !value.trim() || value.length>max || /[<>\u0000-\u0008]/.test(value)) fail(label);};
const id=value=>{if(typeof value!=='string' || !/^[a-z][a-z0-9-]{0,49}$/.test(value)) fail(`invalid id ${value}`);};
const unique=(values,label)=>{if(new Set(values).size!==values.length) fail(`duplicate ${label}`);};
const domainList=list=>{if(!Array.isArray(list) || !list.length || list.some(value=>!fields.has(value))) fail('unknown display domain');};
const date=value=>typeof value==='string' && /^\d{4}-\d{2}-\d{2}$/.test(value) && new Date(value).toISOString().slice(0,10)===value;
export function validateKnowledge(data) {
  if(data?.version!==1 || !Array.isArray(data.concepts) || !Array.isArray(data.resources) || !data.directions || !data.topics) fail('invalid envelope');
  unique(data.concepts.map(c=>c.id),'concept');unique(data.resources.map(r=>r.id),'resource');
  const concepts=new Map(data.concepts.map(c=>[c.id,c]));
  for(const concept of data.concepts) {
    id(concept.id);text(concept.label,'concept label',80);text(concept.summary,'concept summary',240);domainList(concept.domains);
    if(!['field','activity','subject'].includes(concept.kind)) fail('concept kind');
    for(const key of ['broader','related']) if(!Array.isArray(concept[key]) || concept[key].some(value=>value===concept.id || !concepts.has(value))) fail('unknown concept edge');
    const walk=(current,seen)=>{if(seen.has(current.id)) fail('broader cycle');for(const parent of current.broader) walk(concepts.get(parent),new Set([...seen,current.id]));};walk(concept,new Set());
  }
  for(const [topic,groups] of Object.entries(data.directions)) {
    id(topic);if(!Array.isArray(groups) || !groups.length) fail('empty directions');unique(groups.map(g=>g.id),'direction');
    for(const group of groups) {
      id(group.id);text(group.icon,'icon',8);text(group.title,'direction title',80);text(group.description,'description',160);domainList(group.domains);
      if(!Array.isArray(group.activities) || !group.activities.length) fail('activities');
      unique(group.activities.map(a=>a.id),'activity');
      for(const activity of group.activities) {id(activity.id);text(activity.title,'activity title',80);text(activity.description,'activity description',400);text(activity.label,'activity label',40);}
    }
  }
  for(const [key,topic] of Object.entries(data.topics)) {id(key);domainList(topic.ids);for(const name of ['root','label','title']) text(topic[name],`topic ${name}`,80);}
  const resources=new Set(data.resources.map(r=>r.id));
  for(const resource of data.resources) {
    id(resource.id);domainList(resource.domains);if(!resource.domains.includes(resource.domain)) fail('primary domain missing');
    for(const key of ['name','summary','reason','kind','source']) text(resource[key],`${resource.id}.${key}`,key==='name'?80:1500);
    const url=new URL(resource.url);if(resource.url.length>2048 || /[\"<>\s]/.test(resource.url) || !['https:','http:'].includes(url.protocol) || url.username || url.password) fail('unsafe source URL');
    if(!date(resource.checkedOn) || resource.checkedOn>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date())) fail('checkedOn');
    if(resource.reviewAfter!==null && !date(resource.reviewAfter)) fail('reviewAfter');
    if(!['published','draft'].includes(resource.reviewStatus) || !['try','continue','study'].includes(resource.group)) fail('resource status/group');
    if(!Array.isArray(resource.conceptIds) || resource.conceptIds.some(value=>!concepts.has(value))) fail('unknown resource concept');
    if(!Array.isArray(resource.conditions) || resource.conditions.some(pair=>!Array.isArray(pair) || pair.length!==2 || pair.some(value=>typeof value!=='string'))) fail('conditions');
    for(const key of ['host','child']) if(resource[key] && !resources.has(resource[key])) fail(`unknown ${key}`);
    if(resource.type==='event' && !date(resource.date)) fail('event requires date');
  }
  return data;
}
export async function buildKnowledge() {
  const data=validateKnowledge(JSON.parse(await readFile(new URL('../data/knowledge.json',import.meta.url),'utf8')));
  const runtime={concepts:data.concepts,topics:data.topics,directions:Object.fromEntries(Object.entries(data.directions).map(([topic,groups])=>[topic,groups.map(g=>[g.id,g.icon,g.title,g.description,g.domains,g.activities.map(a=>[a.title,a.description,a.label])])])),resources:Object.fromEntries(data.resources.filter(r=>r.reviewStatus==='published').map(({id,...resource})=>[id,resource]))};
  await writeFile(new URL('../knowledge-data.mjs',import.meta.url),`// Generated by npm run knowledge:build. Edit data/knowledge.json instead.\nexport default ${JSON.stringify(runtime,null,2)};\n`);
  return runtime;
}
if(process.argv[1]===fileURLToPath(import.meta.url)) {
  if(process.argv.includes('--check')) {validateKnowledge(JSON.parse(await readFile(new URL('../data/knowledge.json',import.meta.url),'utf8')));console.log('Knowledge valid');}
  else {const data=await buildKnowledge();console.log(`Built ${Object.keys(data.resources).length} resources and ${data.concepts.length} concepts`);}
}
